### ISSUE TITLE
Profile 화면 - 마이페이지, 타 유저 상세 페이지 UI

### ISSUE THREAD

**Issue by dollyishere** [Cheffi-Git/Cheffi-Android#29]
# Issue: :dart: Feature

Profile 화면 - 마이페이지, 타 유저 상세 페이지 UI

# Description

마이페이지, 타 유저 상세 페이지 UI 작업

# ToDo

* [x] icon 교체 작업
* [ ] review card case 별 enum class화, case 별 ui 정형화 => 이후 전국 트렌드 작업 때 처리할 예정
* [x] 마이페이지 app bar 제작 (타 유저 프로필과 동시 사용 가능)
* [x] 쉐피 코인 구매 블록 제작
* [x] 마이페이지 게시물, 팔로워, 팔로잉 숫자 블록 제작
* [x] 마이페이지 팔로우/언팔로우/프로필 수정 버튼 제작
* [x] 마이페이지일 시 코인 수, 포인트 수 확인 가능하도록 설정 및 관련 ui 구현
* [x] 쉐피 chip 제작
* [x] 쉐피 chip 2줄 이상 넘어갈 시 버튼으로 확장/축소 가능하도록 기능 구현
* [x] 마이페이지 내 게시물/구매게시물/찜한 게시물 tab 제작
* [x] 마이페이지&프로필에서 review card 이미지&타임블록만 보이도록 변경(작성자 본인일시/구매했을 시의 케이스는 차후 조정)
* [x] Routing 연결 (기존 리뷰 상세, 프로필 라우터 정형화(Screens)

# ScreenShot/Video

https://github.com/Cheffi-Git/Cheffi-Android/assets/109561384/41a54a84-b938-4557-a522-c6e538546b08

# ETC

* navigation bottom bar 다른 item 눌러 타 화면(전국 트렌드, 맛집 등록, 마이페이지)로 넘어간 후, 다시 홈으로 돌아가는 버튼 누를 시 앱 강제 종료 오류 발생. [이 오류](https://issuetracker.google.com/issues/265838050?pli=1)는 아닌 듯 하며, 중첩 scaffold 같은 홈 내부 요소 이슈도 아니었음(내부 주석 처리 뒤에도 오류 발생)
* 리뷰 카드 개편(케이스 별로 UI 조정)은 타 브랜치에서 진행할 예정
![image](https://github.com/Cheffi-Git/Cheffi-Android/assets/109561384/4d9d4d79-be21-4048-98bd-9bbd5fe26996)
* 해당 부분 tabrow 야매 구현

https://github.com/Cheffi-Git/Cheffi-Android/assets/109561384/65206c91-15bb-4fa9-89cc-5e90af36092f

* 여러 방법(tabrow 사이에 두고 divider 좌우 설치, box로 배경에 divider 깔고 tabrow padding 주기, tabIndicator 자체 Modifier width 주기 등)을 써봤는데도 tab Indicator 초기 설정 때문에 안되는 것 같아 좌우 tab 선택할 때만 padding 주는 식으로 처리, 대신 tab 움직임이 동적임
