### ISSUE TITLE
Trend 화면 - 전국 트렌드 UI_리뷰 카드 코드 리팩토링

### ISSUE THREAD

**Issue by dollyishere** [Cheffi-Git/Cheffi-Android#33]
# Issue: :dart: Feature

Trend 화면 - 전국 트렌드 UI_리뷰 카드 코드 리팩토링

# Description

전국 트렌드 UI, 리뷰 카드 코드 리팩토링, 바텀 네비게이션 이슈 고칠 예정

# ToDo

* [ ] 전국 트렌드 UI
* [ ] 리뷰 카드 코드 리팩토링
* [ ] 바텀 네비게이션 바 이슈(홈 다시 이동 시 앱 자동 종료) 수정
* [ ] 차후 추가

# ScreenShot/Video

스크린샷 & 비디오를 업로드해 주세요.

# ETC

기타 사항이 있다면 작성해주세요.
